### ISSUE TITLE
[games] Othello does not start 

### ISSUE THREAD

**Issue by wamanuz** [smab/playhouse-web#64]
I get "`Loading failed: name 'handler' is not defined`" 

```
Traceback (most recent call last):
  File "/home/mackan/programmering/mvk/playhouse-web/src/config.py", line 516, in post
    manager.load_game()
  File "/home/mackan/programmering/mvk/playhouse-web/src/manager.py", line 104, in load_game
    game.init()
  File "/home/mackan/programmering/mvk/playhouse-web/src/lightgames.py", line 256, in init
    self.reset()
  File "src/games/othello.py", line 30, in reset
    set_description(self, handler)
NameError: name 'handler' is not defined
```

**Comment by wamanuz** [comment]
And I still believe that implementing the rules as a template variable is the best way.
